spring.application.name=FileManagerApplication
jwt.secret=your_very_long_secret_key_here_at_least_32_chars!
jwt.expiration=3600000
# expiration time in milliseconds (e.g., 1 hour)
spring.profiles.active=dev

# PostgreSQL settings
spring.datasource.url=jdbc:postgresql://localhost:5432/File_manager_system
spring.datasource.username=postgres
spring.datasource.password=Nender798/
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.open-in-view=false